import "@radix-ui/themes/styles.css"
import "./theme-config.css"
import "./globals.css"
import NavBar from "./NavBar"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Theme, ThemePanel } from "@radix-ui/themes"

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body className={inter.className}>
        <Theme
          appearance="light"
          accentColor="violet"
          grayColor="slate"
          radius="large"
        >
          <NavBar />
          <main className="p-5">{children}</main>
        </Theme>
      </body>
    </html>
  )
}
